core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "core"


urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("help", views.help_request, name="help"),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    # Password reset URLs
    path("password_reset/", auth_views.PasswordResetView.as_view(
        template_name="accounts/password_reset.html",
        email_template_name="accounts/password_reset_email.html",
        subject_template_name="accounts/password_reset_subject.txt",
        success_url="done/"
    ), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"
    ), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html",
        success_url="done/"
    ), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_complete.html"
    ), name="password_reset_complete"),
    path("account", views.account_request, name="account"),
    path("account/edit", views.edit_account_request, name="edit_account"),
    path("account/edit_profile", views.edit_profile_request, name="edit_profile"),
    path(
        "account/edit_profile/remove_avatar",
        views.remove_avatar_request,
        name="remove_avatar",
    ),
    path("account/strike/<int:userID>", views.strike_request, name="request strike"),
    path(
        "account/remove_strike/<int:userID>",
        views.remove_strike_request,
        name="remove strike",
    ),
    path("account/crush/<int:userID>", views.crush_request, name="request crush"),
    path("account/remove_crush", views.remove_crush_request, name="remove crush"),
    path("account/toggle_active", views.toggle_active_request, name="toggle_active"),
    path("edit_pairings", views.edit_pairs_request, name="edit_pairings"),
    path(
        "edit_pairings/create_new",
        views.create_pairings_request,
        name="create_pairings",
    ),
    path("edit_pairings/push", views.push_pairings_request, name="push_pairings"),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from core.models import Profile
from cloudinary.forms import CloudinaryFileField


# Create your forms here.


class NewUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = user.username
        user.username = user.first_name + "_" + user.last_name
        if commit:
            user.save()
        return user


class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class UpdateProfileForm(forms.ModelForm):
    # avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    pronouns = forms.CharField(max_length=100, required=False)
    phone = forms.CharField(max_length=100, required=False)
    image = forms.ImageField(label="", required=False, widget=forms.FileInput)

    class Meta:
        model = Profile
        fields = ["pronouns", "phone", "image"]

lunchTag/templates/accounts/account.html
{% extends "header.html" %}
{% load static %}
{% load cloudinary %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">

            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column">
                            <div class="align-items-right">
                                <a class="float-right" href="/account/edit_profile">
                                    <img alt="edit_profile" src="{% static 'edit_icon.png' %}">
                                </a>
                            </div>
                            <div class="align-items-center text-center">
                                {% if user_profile.image is not None %}
                                <img src="{{ user_profile.image.url }}" alt="Admin" class="rounded-circle" width="150">
                                {% else %}
                                <img src="{% static 'default.png' %}" alt="Admin" class="rounded-circle" width="150">
                                {% endif %}
                                <div class="mt-3">
                                    <h4>{{ user.first_name }} {{ user.last_name }}</h4>
                                    <p class="text-secondary mb-1">{{ user_profile.pronouns }}</p>
                                    <p class="text-muted font-size-sm">{{ user_profile.phone }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-12">
                                <a class="float-right" href="/account/edit"><img alt="edit_account"
                                        src="{% static 'edit_icon.png' %}"></a>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">First Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user.first_name }}
                            </div>
                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Last Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user.last_name }}
                            </div>
                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user.email }}
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <h4 class="mb-0">Secret Crush</h4>
                            </div>
                            <div class="col-sm-6 text-secondary">
                                <p class="mb-0 float-right"><small>(select up to 1)</small></p>
                            </div>
                        </div>
                        <hr>

                        {% if user_profile.crush != none %}
                        <div class="row">
                            <div class="col-sm-10">
                                <h6 class="mb-3">{{user_profile.crush.first_name}} {{user_profile.crush.last_name}}</h6>
                            </div>
                            <div class="col-sm-2 text-secondary">
                                <a class="float-right text-decoration-none" style="color:gray"
                                    href="/account/remove_crush"><small>remove</small></a>
                            </div>
                        </div>
                        {% endif %}

                        <div class="dropdown">
                            {% if user_profile.crush != none %}
                            <button class="btn btn-secondary dropdown-toggle mt-2" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Change Crush
                            </button>
                            {% else %}
                            <button class="btn btn-secondary dropdown-toggle mt-2" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Add Crush
                            </button>
                            {% endif %}
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% for user in allusers %}
                                {% if not user.is_superuser %}
                                {% if user != user_profile.crush and user != request.user and user not in userstrikes %}
                                <a class="dropdown-item" href="account/crush/{{user.id}}">{{user.first_name}}
                                    {{user.last_name}}</a>
                                {% endif %}
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <h4 class="mb-0">Strikes</h4>
                            </div>
                            <div class="col-sm-6 text-secondary">
                                <p class="mb-0 float-right"><small>(visible only to you)</small></p>
                            </div>
                        </div>
                        <hr>

                        {% for user in userstrikes %}
                        <div class="row">
                            <div class="col-sm-10">
                                <h6 class="mb-3">{{user.first_name}} {{user.last_name}}</h6>
                            </div>
                            <div class="col-sm-2 text-secondary">
                                <a class="float-right text-decoration-none" style="color:gray"
                                    href="/account/remove_strike/{{user.id}}"><small>remove</small></a>
                            </div>
                        </div>
                        {% endfor %}

                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle mt-2" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Add Strike
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                {% for user in allusers %}
                                {% if not user.is_superuser %}
                                {% if user not in userstrikes and user != request.user and user != user_profile.crush %}
                                <a class="dropdown-item" href="account/strike/{{user.id}}">{{user.first_name}}
                                    {{user.last_name}}</a>
                                {% endif %}
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-12 align-items-center text-center">
                {% if user_profile.active %}
                <a class="btn btn-outline-danger mt-4" href="account/toggle_active">Opt Out of Lunch
                    Tag<br><small>(Lasts until you opt back in)</small></a>
                {% else %}
                <a class="btn btn-outline-success mt-4" href="account/toggle_active">Opt In to Lunch Tag</a>
                {% endif %}
            </div>



        </div>
    </div>
</div>

{% endblock %}

lunchTag/templates/accounts/edit_account.html
{% extends "header.html" %}
{% load static %}
{% load cloudinary %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block content %}
<div class="container">
	<div class="main-body">
		<div class="row gutters-sm">
			<div class="col-md-4 mb-3">
				<div class="card">
					<div class="card-body">
						<div class="d-flex flex-column align-items-center text-center">
							{% if user_profile.image is not None %}
							<img src="{{ user_profile.image.url }}" alt="Admin" class="rounded-circle" width="150">
							{% else %}
							<img src="{% static 'default.png' %}" alt="Admin" class="rounded-circle" width="150">
							{% endif %}
							<div class="mt-3">
								<h4>{{ user.first_name }} {{ user.last_name }}</h4>
								<p class="text-secondary mb-1">He/Him</p>
								<p class="text-muted font-size-sm">(720) 724-0751</p>
							</div>
						</div>
					</div>
				</div>
			</div>


			<div class="col-md-8">
				<form method="POST" class="form-edit">
					{% csrf_token %}
					<div class="card mb-3">
						<div class="card-body">
							<div class="row">
								<div class="col-sm-3">
									<h6 class="mb-0">First Name</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<div class="fieldWrapper">
										<label for="{{ form.first_name.id_for_label }}" class="sr-only">First
											Name</label>
										<input type="name" name="{{ user_form.first_name.html_name }}"
											id="inputFirstName" class="form-control" value="{{ user.first_name }}"
											required autofocus>
									</div>
								</div>
							</div>
							<hr>

							<div class="row">
								<div class="col-sm-3">
									<h6 class="mb-0">Last Name</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<div class="fieldWrapper">
										<label for="{{ form.last_name.id_for_label }}" class="sr-only">Last name</label>
										<input type="name" name="{{ user_form.last_name.html_name }}" id="inputLastName"
											class="form-control" value="{{ user.last_name }}" required autofocus>
									</div>
								</div>
							</div>
							<hr>

							<div class="row">
								<div class="col-sm-3">
									<h6 class="mb-0">Email</h6>
								</div>
								<div class="col-sm-9 text-secondary">
									<div class="fieldWrapper">
										{{ user_form.email.errors }}
										<label for="{{ form.email.id_for_label }}" class="sr-only">Email</label>
										<input type="email" name="{{ user_form.email.html_name }}" id="inputEmail"
											class="form-control" value="{{ user.email }}" required autofocus>
									</div>
								</div>
							</div>
							<hr>

							<div class="row">
								<div class="col-sm-12">
									<button class="btn btn-info" type="submit">Save</button>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div>

			<div class="col-md-6">
				<div class="card mb-3">
					<div class="card-body">
						<div class="row">
							<div class="col-sm-6">
								<h4 class="mb-0">Secret Crush</h4>
							</div>
							<div class="col-sm-6 text-secondary">
								<p class="mb-0 float-right"><small>(select up to 1)</small></p>
							</div>
						</div>
						<hr>

						{% if user_profile.crush != none %}
						<div class="row">
							<div class="col-sm-10">
								<h6 class="mb-3">{{user_profile.crush.first_name}} {{user_profile.crush.last_name}}</h6>
							</div>
						</div>
						{% endif %}

					</div>
				</div>
			</div>

			<div class="col-md-6">
				<div class="card mb-3">
					<div class="card-body">
						<div class="row">
							<div class="col-sm-6">
								<h4 class="mb-0">Strikes</h4>
							</div>
							<div class="col-sm-6 text-secondary">
								<p class="mb-0 float-right"><small>(visible only to you)</small></p>
							</div>
						</div>
						<hr>

						{% for user in userstrikes %}
						<div class="row">
							<div class="col-sm-10">
								<h6 class="mb-3">{{user.first_name}} {{user.last_name}}</h6>
							</div>
						</div>
						{% endfor %}

					</div>
				</div>
			</div>

		</div>
	</div>
</div>

{% endblock %}

lunchTag/templates/accounts/edit_profile.html
{% extends "header.html" %}
{% load static %}
{% load cloudinary %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">

            <div class="col-md-4 mb-3">
                <div class="card align-items-center text-center">
                    <div class="card-body">
                        <div class="d-flex flex-column">
                            <form method="POST" class="form-edit" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="col-md-12 align-items-center text-center">
                                    {% if user_profile.image is not None %}
                                    <div class="row">
                                        <img src="{{ user_profile.image.url }}" alt="Admin" class="rounded-circle"
                                            width="150">
                                    </div>
                                    <div class="row align-items-center mt-1">
                                        <label for="{{ profile_form.image.id_for_label }}"
                                            class="btn btn-outline-primary">
                                            <small>Change Profile Picture</small><input type="file"
                                                style="display: none" name="{{ profile_form.image.html_name }}"
                                                accept="image/*" id="id_image">
                                        </label>
                                    </div>
                                    <div class="row align-items-center">
                                        <a class="btn btn-outline-danger btn-sm"
                                            href="edit_profile/remove_avatar">Remove</a>
                                    </div>
                                    {% else %}
                                    <div class="row">
                                        <img src="{% static 'default.png' %}" alt="Admin" class="rounded-circle"
                                            width="150">
                                    </div>
                                    <div class="row">
                                        <label for="{{ profile_form.image.id_for_label }}"
                                            class="btn btn-outline-success">
                                            <small>Upload Profile Picture</small><input type="file"
                                                style="display: none" name="{{ profile_form.image.html_name }}"
                                                accept="image/*" id="id_image">
                                        </label>
                                    </div>
                                    {% endif %}
                                </div>

                                <div class="mt-3">
                                    <h4 class="mb-3">{{ user.first_name }} {{ user.last_name }}</h4>
                                    <div class="row mb-2">
                                        <div class="fieldWrapper">
                                            <label for="{{ profile_form.pronouns.id_for_label }}"
                                                class="sr-only">Pronouns</label>
                                            <input type="foo" name="{{ profile_form.pronouns.html_name }}"
                                                id="inputPronouns" class="form-control"
                                                value="{{ user_profile.pronouns }}">
                                        </div>
                                    </div>

                                    <div class="row mb-2">
                                        <div class="fieldWrapper">
                                            <label for="{{ profile_form.phone.id_for_label }}" class="sr-only">Phone
                                                Number (or easiest contact)</label>
                                            <input type="foo" name="{{ profile_form.phone.html_name }}" id="inputPhone"
                                                class="form-control" value="{{ user_profile.phone }}">
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-sm-12">
                                            <button class="btn btn-info" type="submit">Save</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                        </div>

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">First Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user.first_name }}
                            </div>
                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Last Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user.last_name }}
                            </div>
                        </div>
                        <hr>

                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{ user.email }}
                            </div>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <h4 class="mb-0">Secret Crush</h4>
                            </div>
                            <div class="col-sm-6 text-secondary">
                                <p class="mb-0 float-right"><small>(select up to 1)</small></p>
                            </div>
                        </div>
                        <hr>

                        {% if user_profile.crush != none %}
                        <div class="row">
                            <div class="col-sm-10">
                                <h6 class="mb-3">{{user_profile.crush.first_name}} {{user_profile.crush.last_name}}</h6>
                            </div>
                        </div>
                        {% endif %}

                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <h4 class="mb-0">Strikes</h4>
                            </div>
                            <div class="col-sm-6 text-secondary">
                                <p class="mb-0 float-right"><small>(visible only to you)</small></p>
                            </div>
                        </div>
                        <hr>

                        {% for user in userstrikes %}
                        <div class="row">
                            <div class="col-sm-10">
                                <h6 class="mb-3">{{user.first_name}} {{user.last_name}}</h6>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

lunchTag/templates/accounts/login.html
{% extends "header.html" %}
{% load static %}
{% block content %}
{% load cloudinary %}

<div class="text-center">
  <form method="POST" class="form-signin">

    {% csrf_token %}
    <img class="mb-4" src="{% static 'bulldog.png' %}" alt="" width="100" height="100">
    <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

    {{ login_form.non_field_errors }}
    <div class="fieldWrapper">
      {{ login_form.username.errors }}
      <label for="{{ form.username.id_for_label }}" class="sr-only">Email</label>
      <input type="username" name="{{ login_form.username.html_name }}" id="inputEmail" class="form-control"
        placeholder="Email" required autofocus>
    </div>
    <div class="fieldWrapper">
      {{ login_form.password.errors }}
      <label for="{{ form.password.id_for_label }}" class="sr-only">Password</label>
      <input type="password" name="{{ login_form.password.html_name }}" id="inputPassword" class="form-control"
        placeholder="Password" required>
    </div>

    <button class="btn btn-lg btn-primary btn-block mt-2" type="submit">Login</button>
    <p class="text-center mt-2">
      <a href="{% url 'core:password_reset' %}">Forgot your password?</a>
    </p>
    <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>

  </form>
</div>

{% endblock %}

lunchTag/templates/accounts/password_reset.html
{% extends "header.html" %}
{% load static %}
{% block content %}

<div class="text-center">
  <form method="POST" class="form-signin">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'bulldog.png' %}" alt="" width="100" height="100">
    <h1 class="h3 mb-3 font-weight-normal">Reset Your Password</h1>
    <p class="text-muted mb-4">Enter your email address and we'll send you a link to reset your password.</p>

    {% if form.errors %}
      <div class="alert alert-danger">
        {% for field, errors in form.errors.items %}
          {% for error in errors %}
            <div>{{ error }}</div>
          {% endfor %}
        {% endfor %}
      </div>
    {% endif %}

    <div class="fieldWrapper">
      <label for="{{ form.email.id_for_label }}" class="sr-only">Email</label>
      <input type="email" name="{{ form.email.html_name }}" id="inputEmail" class="form-control"
        placeholder="Email address" required autofocus>
    </div>

    <button class="btn btn-lg btn-primary btn-block mt-3" type="submit">Send Reset Link</button>
    <p class="text-center mt-3">
      <a href="{% url 'core:login' %}">Back to Login</a>
    </p>
  </form>
</div>

{% endblock %}

lunchTag/templates/accounts/password_reset_complete.html
{% extends "header.html" %}
{% load static %}
{% block content %}

<div class="text-center">
  <div class="form-signin">
    <img class="mb-4" src="{% static 'bulldog.png' %}" alt="" width="100" height="100">
    <h1 class="h3 mb-3 font-weight-normal">Password Reset Complete</h1>
    <div class="alert alert-success">
      <p>Your password has been successfully reset!</p>
      <p>You can now log in with your new password.</p>
    </div>
    <p class="text-center mt-3">
      <a href="{% url 'core:login' %}" class="btn btn-primary">Log In</a>
    </p>
  </div>
</div>

{% endblock %}

lunchTag/templates/accounts/password_reset_done.html
{% extends "header.html" %}
{% load static %}
{% block content %}

<div class="text-center">
  <div class="form-signin">
    <img class="mb-4" src="{% static 'bulldog.png' %}" alt="" width="100" height="100">
    <h1 class="h3 mb-3 font-weight-normal">Check Your Email</h1>
    <div class="alert alert-info">
      <p>We've sent you an email with instructions to reset your password.</p>
      <p>If you don't see the email in your inbox, please check your spam folder.</p>
    </div>
    <p class="text-center mt-3">
      <a href="{% url 'core:login' %}" class="btn btn-primary">Back to Login</a>
    </p>
  </div>
</div>

{% endblock %}

lunchTag/templates/accounts/password_reset_email.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Password Reset - Lunch Tag</title>
</head>
<body>
    <div style="max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
        <h2 style="color: #333;">Password Reset Request</h2>
        
        <p>Hello,</p>
        
        <p>You're receiving this email because you requested a password reset for your Lunch Tag account.</p>
        
        <p>Please click the link below to reset your password:</p>
        
        <div style="text-align: center; margin: 30px 0;">
            <a href="{{ protocol }}://{{ domain }}{% url 'core:password_reset_confirm' uidb64=uid token=token %}" 
               style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; display: inline-block;">
                Reset Password
            </a>
        </div>
        
        <p>If the button doesn't work, you can copy and paste this link into your browser:</p>
        <p style="word-break: break-all; color: #666;">
            {{ protocol }}://{{ domain }}{% url 'core:password_reset_confirm' uidb64=uid token=token %}
        </p>
        
        <p>This link will expire in 24 hours for security reasons.</p>
        
        <p>If you didn't request this password reset, please ignore this email. Your password will remain unchanged.</p>
        
        <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
        
        <p style="color: #666; font-size: 12px;">
            This email was sent from Lunch Tag. If you have any questions, please contact the administrator.
        </p>
    </div>
</body>
</html>